/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Persistencia.BeneficiariosXml;
import Persistencia.FechasXml;
import controller.Controladora;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Christian D
 */
public class ConsultaAsistentes extends javax.swing.JFrame {

    Controladora control;
    FechasXml datos = new FechasXml();
    BeneficiariosXml datos2= new BeneficiariosXml();
    public ConsultaAsistentes(String nombreSeminario,String fechaEvento){
        initComponents();
        control = new Controladora(this,panelPrincipal);
        control.IconoVentana(this);
        control.IniciarCursor(this);
        try { //Culpa del parse de la fecha string to fecha
            control.LlenarTablaAsistentesSeminarios(tablaAsistentes,datos,nombreSeminario,fechaEvento);
        } catch (ParseException ex) {
            Logger.getLogger(ConsultaAsistentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ConsultaAsistentes() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new interfaz.personalizados.PanelFondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistentes = new javax.swing.JTable();
        cerrar = new javax.swing.JButton();
        correo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Asistentes");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        tablaAsistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asistentes"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane1.setViewportView(tablaAsistentes);

    cerrar.setBackground(new java.awt.Color(51, 153, 0));
    cerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    cerrar.setForeground(new java.awt.Color(255, 255, 255));
    cerrar.setText("Cerrar");
    cerrar.setBorder(null);
    cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    cerrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cerrarActionPerformed(evt);
        }
    });

    correo.setBackground(new java.awt.Color(51, 153, 0));
    correo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    correo.setForeground(new java.awt.Color(255, 255, 255));
    correo.setText("Generar Lista de correos");
    correo.setBorder(null);
    correo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    correo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            correoActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
    panelPrincipal.setLayout(panelPrincipalLayout);
    panelPrincipalLayout.setHorizontalGroup(
        panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addContainerGap(58, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(58, Short.MAX_VALUE))
        .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addGap(119, 119, 119)
            .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(181, 181, 181)
            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelPrincipalLayout.setVerticalGroup(
        panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addContainerGap(59, Short.MAX_VALUE))
    );

    getContentPane().add(panelPrincipal, "card2");

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
      control.GenerarListaCorreos(tablaAsistentes, datos2,"Asistentes");
    }//GEN-LAST:event_correoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAsistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAsistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAsistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAsistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAsistentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton correo;
    private javax.swing.JScrollPane jScrollPane1;
    private interfaz.personalizados.PanelFondo panelPrincipal;
    private javax.swing.JTable tablaAsistentes;
    // End of variables declaration//GEN-END:variables
}
