/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Persistencia.FechasXml;
import controller.Controladora;
import dominio.Ingreso;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian D
 */
public class VentanaRegistrarIngreso extends javax.swing.JFrame {
    
    Controladora control;
    Ingreso ingreso;
    FechasXml datos2 = new FechasXml();
    
    public VentanaRegistrarIngreso() {
        initComponents();
        control = new Controladora(this, panelPrincipal);
        control.IconoVentana(this);
        control.IniciarCursor(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new interfaz.personalizados.PanelFondo();
        totalEfectivo = new javax.swing.JTextField();
        razon = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        totalDebito = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Ingresos");
        setResizable(false);

        totalEfectivo.setText("Monto total en efectivo:");
        totalEfectivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalEfectivoFocusLost(evt);
            }
        });
        totalEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalEfectivoKeyTyped(evt);
            }
        });

        razon.setText("Razón o motivo del ingreso:");
        razon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                razonFocusLost(evt);
            }
        });
        razon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                razonKeyTyped(evt);
            }
        });

        registrar.setBackground(new java.awt.Color(51, 153, 0));
        registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("Registrar Ingreso");
        registrar.setBorder(null);
        registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarMouseClicked(evt);
            }
        });

        atras.setBackground(new java.awt.Color(51, 153, 0));
        atras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");
        atras.setBorder(null);
        atras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione la fecha:");

        totalDebito.setText("Monto total con tarjeta de débito:");
        totalDebito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalDebitoFocusLost(evt);
            }
        });
        totalDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalDebitoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalDebito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalEfectivo)
                            .addComponent(razon, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(totalEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(razon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalEfectivoKeyTyped
        control.EscribirTextfield(totalEfectivo, "Monto total en efectivo:");
        control.ValidarDouble(evt);
    }//GEN-LAST:event_totalEfectivoKeyTyped

    private void totalEfectivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalEfectivoFocusLost
       control.VacioTextfield(totalEfectivo, "Monto total en efectivo:");
    }//GEN-LAST:event_totalEfectivoFocusLost

    private void razonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razonKeyTyped
        control.EscribirTextfield(razon, "Razón o motivo del ingreso:");
        control.ValidarLetras(evt);
    }//GEN-LAST:event_razonKeyTyped

    private void razonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_razonFocusLost
       control.VacioTextfield(razon,"Razón o motivo del ingreso:");
    }//GEN-LAST:event_razonFocusLost

    private void registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseClicked
        boolean y = control.ValidarFecha(fecha);
        if(y==false){
            boolean x = control.ComprobarFecha(fecha.getDate(),datos2);
            if(x==false)
                control.ActualizarListaFecha(fecha.getDate(),datos2);
            if(control.ValidarRegistroIngreso(this, totalEfectivo, totalDebito, razon, fecha)){
                ingreso = new Ingreso(Double.parseDouble(totalEfectivo.getText()), Double.parseDouble(totalDebito.getText()),razon.getText(),fecha.getDate());
                control.ActualizarListaIngresos(ingreso,fecha.getDate(),datos2);
                control.RestablecerCamposIngreso(totalEfectivo, totalDebito, razon, fecha);
            }
            else
                JOptionPane.showMessageDialog(null, "Por favor Llene los campos correctamente.");
                
        }
        
        
    }//GEN-LAST:event_registrarMouseClicked

    private void totalDebitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalDebitoKeyTyped
        control.EscribirTextfield(totalDebito, "Monto total con tarjeta de débito:");
        control.ValidarDouble(evt);
    }//GEN-LAST:event_totalDebitoKeyTyped

    private void totalDebitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalDebitoFocusLost
        control.VacioTextfield(totalDebito, "Monto total con tarjeta de débito:");
    }//GEN-LAST:event_totalDebitoFocusLost

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        VentanaPrincipal ventana = new VentanaPrincipal();
        //control.LlenarTablaIngresos(ventana.tablaIngreso, ventana.ingresoTotal, ventana.saldoTotal,datos2);
        control.IntercambiarPaneles(ventana.panelIngresosyEgresos, ventana.panelBeneficiarios, ventana.panelSeminarios, ventana.panelSesiones,ventana.panelSeminariosD);
        control.ActivarVentana(ventana, this);
    }//GEN-LAST:event_atrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private interfaz.personalizados.PanelFondo panelPrincipal;
    private javax.swing.JTextField razon;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField totalDebito;
    private javax.swing.JTextField totalEfectivo;
    // End of variables declaration//GEN-END:variables
}
